version: '3.9'

services:
  seaweedfs-master:
    image: 'chrislusf/seaweedfs:4.13'
    environment:
      - SERVICE_USER_S3
      - SERVICE_PASSWORD_S3
    volumes:
      - 'seaweedfs-s3-data:/data'
      -
        type: bind
        source: ./base-config.json
        target: /base-config.json
    entrypoint: "sh -c 'sed \"s/env:AWS_ACCESS_KEY_ID/$SERVICE_USER_S3/g\" /base-config.json > /base1-config.json && sed \"s/env:AWS_SECRET_ACCESS_KEY/$SERVICE_PASSWORD_S3/g\" /base1-config.json > /config.json && weed server -dir=/data -master.port=9333 -s3 -s3.port=8333 -s3.config=/config.json'"
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --spider -q http://0.0.0.0:9333/cluster/status; [ $$? -le 8 ]'
      interval: 10s
      timeout: 5s
      retries: 10

  seaweedfs-volume:
    image: 'chrislusf/seaweedfs:4.13'
    command: 'volume -mserver="seaweedfs-master:9333" -ip.bind=0.0.0.0 -port=8080 -max=100'
    volumes:
      - 'seaweedfs-volume-data:/data'
    depends_on:
      seaweedfs-master:
        condition: service_healthy

  seaweedfs-admin:
    image: 'chrislusf/seaweedfs:4.13'
    environment:
      - SERVICE_USER_ADMIN
      - SERVICE_PASSWORD_ADMIN
    command: "sh -c 'admin -master=seaweedfs-master:9333 -adminUser=$SERVICE_USER_ADMIN -adminPassword=$SERVICE_PASSWORD_ADMIN -port=23646 -dataDir=/data'"
    volumes:
      - 'seaweedfs-admin-data:/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --spider -q http://0.0.0.0:23646; [ $$? -le 8 ]'
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      seaweedfs-master:
        condition: service_healthy

volumes:
  seaweedfs-s3-data:
  seaweedfs-volume-data:
  seaweedfs-admin-data:
